import type { Metadata } from "next";
import { Geist_Mono, Funnel_Sans, Playfair_Display } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider";
import { AIAssistant } from "@/components/ai-assistant";

const playfairDisplayHeading = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-heading",
});

const funnelSans = Funnel_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" suppressHydrationWarning
       
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        funnelSans.variable,
        playfairDisplayHeading.variable,
        geistMono.variable
      )}
        >
            <body className="font-inter">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                    
                </ThemeProvider>
                <AIAssistant />
            </body>
        </html>
    )
}


